### PR TITLE
Allow multiple refspecs on fetch, pull and push

### PR DESCRIPTION
**Pull request by nfantone**
Enables users to specify `branch` parameter as an _array_ of strings in _pull_, _push_ and _fetch_ `git` commands.

Example:

```javascript
git.push('origin', ['develop', 'master'], { quiet: true, args: '--tags' }, done);
```

Generates the following valid shell command:

```sh
$ git push origin develop master --tags
```

### CODE REVIEW

**Comment by stevelacy** [comment]
1.8.0

**Comment by nfantone** [comment]
Not on npm yet?

**Comment by stevelacy** [comment]
Published - was waiting on the build

**Comment by nfantone** [comment]
Realised I didn't update the docs for the API of the modified methods.

**Comment by stevelacy** [comment]
Send a PR if you want, I'll probably get around to it later on next month.

**Pull request merged**
