### PR TITLE
Add git.fetch and update docs

### PR DESCRIPTION
**Pull request by h-no**
I needed git fetch for a project, so... here it is if you want it.

### CODE REVIEW

**Comment by stevelacy** [comment]
Thanks, could you write a test for fetch?

**Comment by h-no** [comment]
Sure, no problems. Stay tuned :)

**Comment by h-no** [comment]
Ok, testing towards https://github.com/stevelacy/git-test 
Hope you're happy with the code, tried to match existing code style etc.

**Comment by stevelacy** [comment]
Nicely done, you can remove the globals comment as it is added to .jshintrc

**Pull request merged**
