### PR TITLE
Adds disableMessageRequirement option

### PR DESCRIPTION
**Pull request by jimthedev**
I have a use case which requires me to pass a raw argument string to git commit. A user will set the message in this raw string. Setting disableMessageRequirement to true will allow libraries to disable the sensible defaults in special cases.

### CODE REVIEW

**Comment by jimthedev** [comment]
Closes #72

**Comment by stevelacy** [comment]
Please add a test and documentation for this addition.

**Comment by jimthedev** [comment]
Added tests, docs, and rebased. Should be set. Fixes #72

**Comment by stevelacy** [comment]
Excellent, thank you

**Comment by jimthedev** [comment]
Thanks for the merge. :+1

**Comment by stevelacy** [comment]
published v1.2.0

**Pull request merged**
