### PR TITLE
New API

### PR DESCRIPTION
**Pull request by gucong3000**
- Add `git.lsFiles`
- Update `git.catFile`
- Add `git.blame`
- Update `git.diff`
- add `git.util`
  - add `git.util.blame`
  - add `git.util.diff`
  - add `git.util.log`
  - add `git.util.lsFiles`
  - add `git.util.mapStream`
  - add `git.util.parseDate`
  - add `git.util.readStream`
  - add `git.util.spawn`

### CODE REVIEW

**Comment by stevelacy** [comment]
What does this improve?

**Comment by gucong3000** [comment]
I added two new interfaces: `git.lsFiles` and `git.catFile`
In the process, I moved the code that repeated with `git.diff` and `git.catFile` to `git.util`

**Comment by gucong3000** [comment]
I've done.
@stevelacy please review. thanks a lot.

**Comment by gucong3000** [comment]
I'm trying to move the API document to `jsDoc`
image

**Comment by stevelacy** [comment]
I never asked for jsdoc.

**Comment by gucong3000** [comment]
Please give me some advice.

**Comment by gucong3000** [comment]
@stevelacy I don't quite understand your expectations.

**Comment by gucong3000** [comment]
@stevelacy Whould you please tell me your plan?

**Comment by stevelacy** [comment]
You should have opened an issue describing what you wanted to do, the changes you wanted to make before spending time writing code and sending a PR.
I don't want JSDoc, I don't want random git commands that could be passed through `git.exec` instead.
Only commands that require parsing files (or are very popular) should be added to the main lib.

**Pull request closed without merging**
