### PR TITLE
don't return error when nothing to commit.

### PR DESCRIPTION
**Pull request by ttwthomas**
same as https://github.com/stevelacy/gulp-git/pull/118
not sure why the tests failed in previous PR but it worked on my machine

### CODE REVIEW

**Comment by stevelacy** [comment]
Can you change it to 
```js
&& (String(stdout).indexOf('no changes added to commit') === 0)
```
Reduces length and removes the need for two checks

**Comment by ttwthomas** [comment]
Done :)

**Comment by stevelacy** [comment]
Perfect, thanks!

**Comment by stevelacy** [comment]
published 1.14.0

**Pull request merged**
