### PR TITLE
Added support for git clean

### PR DESCRIPTION
**Pull request by legacybass**
Added support for the git clean command
Added tests for git-clean function

### CODE REVIEW

**Comment by legacybass** [comment]
Looks like the build is failing on the fetch test, which none of my code changed or interacted with. It looks like it's failing to get a tag from github? Am willing to find out what's going wrong, but I don't believe it involves my additions.

**Comment by legacybass** [comment]
Any support on this would be great. Running the same command that the git-fetch test does `git update-ref -d refs/tags/v1.1.1` does not create the folder v1.1.1 in the refs/tags folder. I'm not enough of a git guru to know what's causing this to fail. If anyone has any suggestions on what I'm missing or how to fix this, I'd really appreciate it.

**Comment by legacybass** [comment]
I fixed the issue with fetch, even though it wasn't my code and mine didn't interact with it. Now, however, it appears that the build server didn't clean up correctly. It appears the folder being used in the commit test exists when it tries to create it, and this fails. Since I can't get to the build server to see if it's correctable, is there any way someone with access could look at it and judge if it's able to be repaired (I'm guessing just remove the folder)?

**Comment by stevelacy** [comment]
can you clean up line 8-34? there are way to many if/else, you don't need any else statements.

**Pull request closed without merging**
