### PR TITLE
Fix issue #188

### PR DESCRIPTION
**Pull request by ustieber**
This is my proposed fix for issue #188 . Please review and merge if the fix is OK for you.

### CODE REVIEW

**Comment by stevelacy** [comment]
Do you want to edit the git config on your system to use your github email? right now it shows the "unknown user"

**Comment by ustieber** [comment]
Ah. Sorry for that. Let me take care of it

**Comment by ustieber** [comment]
Hi,

I’ve configured user.name and user.email on my local system for the fork of gulp-git. Anything else? I’m not sure what will be the next step? If I look at the pull request in GitHub, thinks seems to be OK.

Best regards
Uwe Stieber

**Comment by stevelacy** [comment]
You can now do `git commit --amend --author="Author Name <email@address.com>"`
Then force push to your branch `fix_issue_188`

**Comment by ustieber** [comment]
Did it.

Best regards, Uwe

**Comment by stevelacy** [comment]
Perfect, merging

**Pull request merged**
